logging:
  console:
    level: "debug"
  file:
    enable: true
    level: "info"
    dir_path: "logs"
coordinator:
  keypair_path: "keys_for_test/coordinator.key"
  port: 15926
  remote_addr: "127.0.0.1"
  peer_id: "12D3KooWB3LpKiErRF3byUAsCvY6JL8TtQeSCrF5Hw23UoKJ7F88"
  ipc_socket_path: "ipc_socket/coordinator.sock"
  keystore_path: "keystore/coordinator"
  peer_id_whitelist:
    - "12D3KooWQdd3vZB7PQtcGBGxpP52oCXX4X4xCVrqi8r8Ejs6nTg3"
    - "12D3KooWRL6gitv6stQxyERJuraGNVZGQThWXGo9TC2Njf6XFB1X"
    - "12D3KooWERAyoKaecWpu7u9iN9ZaoL2r5ZBtWtkKSZ4rFs2KBWW4"
signer:
  allow_external_address: true
  keypair_path_mapping: { 1: "keys_for_test/signer1.key", 2: "keys_for_test/signer2.key", 3: "keys_for_test/signer3.key" }
  ipc_socket_path: "ipc_socket/"
  keystore_path: "keystore/signer"
  connection_timeout: 5
connection:
  ping_interval: 1
session:
  state_channel_retry_interval: 1
  signing_round1_timeout: 10
  signing_round2_timeout: 10
node:
  keypair_path: "keys_for_test/node.key"
  ipc_socket_path: "ipc_socket/"

  connection_timeout: 5
